### ISSUE TITLE
Non-existing character in an alphabet

### ISSUE THREAD

**Issue by tigertv** [tigertv/secretpy#3]
Conclusions from #2:
Handle exceptions when a character doesn't exist in an alphabet. 
A solution would be either to show an error message or remove non-existing characters from message.

**Comment by ZetaTwo** [comment]
At least for Caesar it would be good to be able to just leave the character in place.

**Comment by tigertv** [comment]
Hi @ZetaTwo ! 
>... just leave the character in place.
Developer decides how to handle this situation, either he use a 'try-catch' or correct input.

**Comment by tigertv** [comment]
Hi @ZetaTwo ! 
>... just leave the character in place.

Developer decides how to handle the situation, either he uses a 'try-catch' or correct input(only characters from alphabet). 
Also developer can use the wrappers 'SaveAll' and 'RemoveAll':
https://github.com/tigertv/secretpy/blob/b87b822cbd9776660e51c4cf7ccbaaeec97faab0/examples/caesar.py#L42L48

**Comment by ZetaTwo** [comment]
> Also developer can use the wrappers 'SaveAll' and 'RemoveAll'

Perfect. This was exactly what I meant. Thank you.

**Comment by tigertv** [comment]
You are welcome!
